[package]
name = "gpt_arb"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "3.0.1"
solana-sdk = "3.0.0"
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
spl-math = "0.3.0"
